CREATE TABLE IF NOT EXISTS CLIENTES(
    COD_CLIENTE VARCHAR(10) NOT NULL,
	NOME VARCHAR(50) NOT NULL,
	EMAIL VARCHAR(50) NOT NULL,
	RUA VARCHAR(50) NOT NULL,
	BAIRRO VARCHAR(50) NOT NULL,
	CIDADE VARCHAR(50) NOT NULL,
	ESTADO VARCHAR(50) NOT NULL,
 PRIMARY KEY (COD_CLIENTE)
);

CREATE TABLE IF NOT EXISTS TELEFONES_CLIENTES(
    COD_TELEFONE VARCHAR(10) NOT NULL,
    COD_CLIENTE VARCHAR(10) NOT NULL,
    TELEFONE VARCHAR(14) NOT NULL,
 PRIMARY KEY (COD_TELEFONE)
);

CREATE TABLE IF NOT EXISTS LIVROS(
    COD_LIVRO VARCHAR(10) NOT NULL,
	VALOR DECIMAL(5,2) NOT NULL,
	ANO_PUBLICACAO INT NOT NULL,
    CATEGORIA VARCHAR(25) NOT NULL,
    TITULO VARCHAR(50) NOT NULL,
    ISBN INT NOT NULL,
    COD_AUTOR VARCHAR(10) NOT NULL,
    COD_EDITORA VARCHAR(10) NOT NULL,
	QTD_ESTOQUE INT NOT NULL,
 PRIMARY KEY (COD_LIVRO)
);

CREATE TABLE IF NOT EXISTS AUTORES(
    COD_AUTOR VARCHAR(10) NOT NULL,
    AUTOR VARCHAR(25) NOT NULL,
    EMAIL VARCHAR(50),
 PRIMARY KEY (COD_AUTOR)
);

CREATE TABLE IF NOT EXISTS EDITORAS(
    COD_EDITORA VARCHAR(10) NOT NULL,
    TELEFONE VARCHAR(50),
    EMAIL VARCHAR(50),
    NOME_CONTATO VARCHAR(50) NOT NULL,
 PRIMARY KEY (COD_EDITORA)
);

CREATE TABLE IF NOT EXISTS PEDIDOS(
    COD_PEDIDO VARCHAR(10) NOT NULL,
    COD_CLIENTE VARCHAR(20) NOT NULL,
    DATA DATE NOT NULL,
	VALOR_PEDIDO DECIMAL(5,2) NOT NULL,
 PRIMARY KEY (COD_PEDIDO)
);

CREATE TABLE IF NOT EXISTS ITENS_PEDIDOS(
    COD_PEDIDO VARCHAR(10) NOT NULL,
	COD_LIVRO VARCHAR(10) NOT NULL,
	QTD_PEDIDO INT NOT NULL,
	VALOR_ITENS DECIMAL(5,2) NOT NULL,
 PRIMARY KEY (COD_PEDIDO, COD_LIVRO)
);

CREATE TABLE IF NOT EXISTS COLABORADORES(
    COD_COLAB VARCHAR(10) NOT NULL,
    NOME VARCHAR(100) NOT NULL,
 PRIMARY KEY (COD_COLAB)
);

CREATE TABLE IF NOT EXISTS CARGOS_COLABORADORES(
    COD_COLAB VARCHAR(10) NOT NULL,
    COD_SAL_CAR VARCHAR(10) NOT NULL,
 PRIMARY KEY (COD_COLAB, COD_SAL_CAR)
);

CREATE TABLE IF NOT EXISTS SALARIOS (
    COD_SAL_CAR VARCHAR(10) NOT NULL,
    DEPARTAMENTO VARCHAR(50) NOT NULL,
    CARGO VARCHAR(50) NOT NULL,
    SALARIO_BASE DECIMAL(10, 2) NOT NULL,
 PRIMARY KEY (COD_SAL_CAR)
);

CREATE TABLE IF NOT EXISTS DEPENDENTES(
    COD_DEPEN VARCHAR(10) NOT NULL,
    COD_COLAB VARCHAR (10) NOT NULL,
    DEPENDENTE VARCHAR(50) NOT NULL,
 PRIMARY KEY (COD_DEPEN)
);